name:                render-diagram
version:             0.1.0.0
license:             AllRightsReserved

dependencies:
- base >= 4.7 && < 5
- megaparsec
- blaze-html
- blaze-markup
- bytestring
- text
- casing
- neat-interpolation
- parser-combinators

default-extensions:
- BlockArguments

executables:
  render-diagrams-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - '"-with-rtsopts=-N -qg -I0"'
    - -O2
